- include/cooperative_perception/detected_object.hpp
The DetectedObjectCache is required for Remote Object Tracking's temporal and spatial alignment.
This PR provides a DetectedObjectCache type that maps an incoming report's ID to its DetectedObjectType.
This cache would be used by a Remote Object Tracking process to support the alignment of the data between process executions. 
#24 
Small enough change that no tests were developed.
> Created DetectedObjectCache type

- include/cooperative_perception/scoring.hpp
- test/test_scoring.cpp
This PR cleans up the scoring implementation. It removes some unused functions and unifies the visitor names used in the scoring process.
Closes #32 
Removing bloat and maintaining consistent naming is a good code hygiene practice. 
All existing unit tests passed.
> Clean up scoring implementation

- include/cooperative_perception/gating.hpp
- test/CMakeLists.txt
- test/test_gating.cpp
This PR adds a function to prune track-to-detection scores. Gating functionality allows us to prune track-to-detection scores that are highly unlikely. This saves some computation during the association stage.
Closes usdot-fhwa-stol/cooperative-perception-core#38
Depends on usdot-fhwa-stol/cooperative-perception-core#37
See description
> Add gating functionality

- include/cooperative_perception/covariance_calibration.hpp
- include/cooperative_perception/ctrv_model.hpp
- include/cooperative_perception/detection.hpp
- include/cooperative_perception/scoring.hpp
- include/cooperative_perception/temporal_alignment.hpp
- include/cooperative_perception/track.hpp
- test/test_detection.cpp
- test/test_host_object_alignment.cpp
- test/test_scoring.cpp
This PR unifies the `detection` and `track` name usages across the library, particularly for template parameter names.
Uses of the word "object" has been replaced with "detection" wherever appropriate. The detection and track variants have been renamed to DetectionVariant and TrackVariant, respectively. Template arguments for non-variant Detections and Tracks have been renamed to DetectionType and TrackType, respectively.
The visitor lambdas now have Doxygen comment blocks explaining the expected types for the auto parameters.
Copyright has been updated on modified files.
The `objectAtTime` and `objectsAtTime` functions have been removed because they are not used in the library.
Closes #44
Unifying the names prevents users and developers from getting confused.
Name changes only. Existing …
> Unify names

- dependencies.cmake
This PR reverts the Eigen library version from 3.4.0 to 3.3.7. Downstream users of this library (so far only CARMA) currently use 3.3.7, but the 3.4.0 interface is not backwards compatible.
Closes #73 
[CDAR-393](https://usdot-carma.atlassian.net/browse/CDAR-393)
See Description
Unit tests were modified in previous changes to prepare for the version change. See #78 and #75.
[CDAR-393]: https://usdot-carma.atlassian.net/browse/CDAR-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert Eigen version to 3.3.7

- include/cooperative_perception/track_management.hpp
The track status values have been changed from `std::string`s to enumerations to provide strong type safety and more robust checks. Enumerations provide better type safety and are less error-prone than string comparisons.
Closes #84 
Track statuses have a finite number of options, so they are good candidates for enumerations. The previous method of storing them as strings is less robust.
Internal change to a class.
> Replace string constants with enumerations

- docs/main.md
- docs/track_management/fixed_threshold_track_manager/add_tentative_track.md
- docs/track_management/fixed_threshold_track_manager/constructor.md
- docs/track_management/fixed_threshold_track_manager/destructor.md
- docs/track_management/fixed_threshold_track_manager/get_all_tracks.md
- docs/track_management/fixed_threshold_track_manager/get_confirmed_tracks.md
- docs/track_management/fixed_threshold_track_manager/get_tentative_tracks.md
- docs/track_management/fixed_threshold_track_manager/main.md
- docs/track_management/fixed_threshold_track_manager/update_track_lists.md
- include/cooperative_perception/track_management.hpp
- test/CMakeLists.txt
- test/test_track_management.cpp
This PR replaces the generic `TrackManager` class with one that only uses a fixed-threshold management policy. The original generic class was unnecessarily complex for our use-case, especially since we were only using the fixed-threshold management policy.
Closes #86 
Closes [CDAR-424](https://usdot-carma.atlassian.net/browse/CDAR-424)
This change significantly simplifies the codebase without affecting performance.
[CDAR-424]: https://usdot-carma.atlassian.net/browse/CDAR-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Replace generic `TrackManager` class

- docs/clustering/cluster/add_detection.md
- docs/clustering/cluster/clear.md
- docs/clustering/cluster/get_centroid.md
- docs/clustering/cluster/get_detections.md
- docs/clustering/cluster/index.md
- docs/clustering/cluster/is_empty.md
- docs/clustering/cluster/remove_detection.md
- docs/clustering/cluster_detections.md
- docs/clustering/point/index.md
- docs/clustering/point/operator_divide.md
- docs/main.md
- include/cooperative_perception/clustering.hpp
- test/CMakeLists.txt
- test/data/test_clustering_disjoint.json
- test/data/test_clustering_overlapping.json
- test/test_clustering.cpp
This PR adds support for clustering detections based on their Euclidean distances. It introduces the `Cluster` class and the `cluster_detections` function. There are some additional detail functions, but they are not part of the public interface.
Closes #87 
Closes [CDAR-423](https://usdot-carma.atlassian.net/browse/CDAR-423)
When there are multiple detections corresponding to the same non-existent track, we need to choose a single representation. Otherwise, we will have duplicated tracks, which can cause association issues in the next iteration. By clustering detections, we can better choose which single detection (or aggregation) will represent the cluster.
Added unit tests.
[CDAR-423]: https://usdot-carma.atlassian.net/browse/CDAR-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
> Add clustering support

- include/cooperative_perception/track_matching.hpp
- test/test_track_matching.cpp
This PR modifies the association implementations to allow for more detections than tracks. Previously, it was implicitly assumed that each detection would have at least one possible track to associate with. However, this is not always the case. When we encounter scenarios with more detections than tracks, the current implementation fails with an indexing error.
The revised implementation pads the underlying cost matrix with phantom tracks until there is a possible (not necessarily optimal) one-to-one association. After the association step, the phantom associations are discarded.
Closes #93 
Closes [CDAR-439](https://usdot-carma.atlassian.net/browse/CDAR-439)
The previous implementation would fail when there are more detections than tracks.
[CDAR-439]: …
> Add support for more detections than tracks

- include/cooperative_perception/clustering.hpp
This PR fixes erasing elements within the `detections` map. The function now properly increments the iterator on erasure.
Closes #95 
[CDAR-440](https://usdot-carma.atlassian.net/browse/CDAR-440)
[CDAR-440]: https://usdot-carma.atlassian.net/browse/CDAR-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix detection erasing in cluster_detections

- include/cooperative_perception/track_management.hpp
This PR fixes the iterator increment in the `TrackManager`'s `update_track_lists` function. Previously, the iterator was not updated properly after erasing an element from `occurrenes_`.
Closes #97 
Closes [CDAR-441](https://usdot-carma.atlassian.net/browse/CDAR-441)
[CDAR-441]: https://usdot-carma.atlassian.net/browse/CDAR-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix `update_track_lists` function implementation

- docs/track_management/fixed_threshold_track_manager/constructor.md
- docs/track_management/fixed_threshold_track_manager/get_promotion_threshold.md
- docs/track_management/fixed_threshold_track_manager/get_removal_threshold.md
- docs/track_management/fixed_threshold_track_manager/main.md
- docs/track_management/fixed_threshold_track_manager/set_promotion_threshold_and_update.md
- docs/track_management/fixed_threshold_track_manager/set_removal_threshold_and_update.md
- include/cooperative_perception/track_management.hpp
- test/test_track_management.cpp
This PR adds getter and setter support for the `TrackManager` class. Users are no longer limited to specifying the threshold values only at compile time. When users set new threshold values, any track within the `TrackManager`'s internal list will be updated according to the new threshold value.
Closes #99
Closes [CDAR-450](https://usdot-carma.atlassian.net/browse/CDAR-450)
Users should have the freedom to modify the threshold values whenever they like.
Unit tests
[CDAR-450]: https://usdot-carma.atlassian.net/browse/CDAR-450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add getters and setters for the `TrackManager`'s thresholds

- cmake/cooperative_perception_coreConfig.cmake
- dependencies.cmake
- package.xml
- src/CMakeLists.txt
This PR adds necessary files and CMake configurations to support being consumed by ROS 2 packages.
Closes #102 
Closes [CDAR-467](https://usdot-carma.atlassian.net/browse/CDAR-467)
The downstream ROS 2 package was previously consuming this library as a source dependency through `FetchContent`/CPM, but we can get `colcon` to build the `multiple_object_tracking` library as a ROS 2 package. Downstream ROS 2 packages can then consume the library through `find_package`.
[CDAR-467]: https://usdot-carma.atlassian.net/browse/CDAR-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add ROS 2 package support

- include/multiple_object_tracking/detail/dlib_extensions.hpp
- include/multiple_object_tracking/track_matching.hpp
This PR fixes an issue that caused incorrect track-to-detection associations for certain scenarios. There was some issue with the implementation for making cost matrices squared. Instead of using dlib::tmp, we are now explicitly creating a new empty matrix then populating the data manually. This operation was also moved into its own function. We can refine the implementation later if needed, but the separate function abstracts the current implementation.
Closes #106 
Closes [CDAR-577](https://usdot-carma.atlassian.net/browse/CDAR-577)
Unit tests
[CDAR-577]: https://usdot-carma.atlassian.net/browse/CDAR-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix making square matrix implementation

- include/multiple_object_tracking/dynamic_object.hpp
- include/multiple_object_tracking/track_management.hpp
- test/test_track_management.cpp
This PR adds track update function for the `FixedThresholdTrackManager` class that allows users to update contained tracks in place. Previously, there was no ability for users to modify tracks after they have been added to the manager.
Closes #113 
usdot-fhwa-stol/carma-platform#2213
Closes [CDAR-596](https://usdot-carma.atlassian.net/browse/CDAR-596)
There was no way to modify tracks' states, so the manager was less useful than it could be.
Unit tests
[CDAR-596]: https://usdot-carma.atlassian.net/browse/CDAR-596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add track state setter for `FixedThresholdTrackManager`

- include/multiple_object_tracking/dynamic_object.hpp
- include/multiple_object_tracking/track_management.hpp
This PR modifies the `FixedThresholdTrackManager` to support `std::variant` types.
The track manager's update_track function used the state_type and state_covariance_type member aliases for the function parameter types, but std::variant track types don't work with this. It's easier to remove those type requirements and refactor later.
The `state` and `state_covariance` types are now template parameters. 
Closes #115 
Closes [CDAR-596](https://usdot-carma.atlassian.net/browse/CDAR-596)
Add support for `std::variant` types.
Unit tests. Manual integration test with downstream project.
[CDAR-596]: https://usdot-carma.atlassian.net/browse/CDAR-596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove `FixedThresholdTrackManager`'s `update_track` function type specifiers

- include/multiple_object_tracking/track_matching.hpp
- test/test_track_matching.cpp
This PR resolves a bug when doing the track-to-detection association step with more tracks than detections. When creating association maps from the association problem results, there was no bounds checking. This would cause an indexing error when there are existing tracks that did not get any associated detections.
Closes #111 
Closes [CDAR-586](https://usdot-carma.atlassian.net/browse/CDAR-586)
Fixes bug
Unit tests. Integration tests.
[CDAR-586]: https://usdot-carma.atlassian.net/browse/CDAR-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add bounds check for creating associations

- include/multiple_object_tracking/dynamic_object.hpp
This PR adds a semantic class field for the `DynamicObject` class. Semantic class information is useful for a variety of applications and is a pretty common attribute (at least for our use cases).
Closes #120 
Closes [CDAR-627](https://usdot-carma.atlassian.net/browse/CDAR-627)
See above
Manually in integration tests.
[CDAR-627]: https://usdot-carma.atlassian.net/browse/CDAR-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add semantic class field for dynamic object

- include/multiple_object_tracking/dynamic_object.hpp
This PR fixes a bug that causes tracks generated from detections to have possibly invalid semantic classes. The `make_track` function now copies the semantic class from the source detection.
Closes #131 
Closes [CDAR-702](https://usdot-carma.atlassian.net/browse/CDAR-702)
Bug fix
Manually in downstream package.
[CDAR-702]: https://usdot-carma.atlassian.net/browse/CDAR-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Copy semantic class when making track

- include/multiple_object_tracking/fusing.hpp
This PR fixes a bug for covariance intersection. It was previously not updating the timestamp, so the fused track was using it's original stamp.
Closes #129 
[CDAR-701](https://usdot-carma.atlassian.net/browse/CDAR-701)
Bug fix
Manually in downstream package.
[CDAR-701]: https://usdot-carma.atlassian.net/browse/CDAR-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update fused track's timestamp

- include/multiple_object_tracking/track_matching.hpp
This PR fixes a bug with track-to-detection cost matrix generation. When generating to cost matrix for track-to-detection scoring, the value range was only 0-100, causing some scores with different floating-point values to get mapped to the same integer value. The integer value range is now between 0-100,000,000.
Closes #112 
Closes [CDAR-587](https://usdot-carma.atlassian.net/browse/CDAR-587)
Bug fix
Manually in downstream packages
[CDAR-587]: https://usdot-carma.atlassian.net/browse/CDAR-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Increase scaled cost value range

- include/multiple_object_tracking/clustering.hpp
The `cluster_detections` function used to hardcode the metric type. Now there is an overload for users to bring their own.
Closes #126
Closes [CDAR-700](https://usdot-carma.atlassian.net/browse/CDAR-700)
Not all users will want to use scaled Euclidean distance when generating clusters. Previously, the `cluster_detections` function did not allow users to bring their own metrics.
Manually in downstream packages.
[CDAR-700]: https://usdot-carma.atlassian.net/browse/CDAR-700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add clustering overload for generic metric

- dependencies.cmake
- test/multiple_object_tracking/test/gmock_matchers.hpp
The GMock matchers were implemented using a newer API that is incompatible with GMock version 1.10. Since most downstream packages (namely, CARMA packages) still use version 1.10, it would be best to revert back to that implementation.
Closes #134 
Closes [CDAR-703](https://usdot-carma.atlassian.net/browse/CDAR-703)
This was preventing downstream, dependent project from building.
Manually.
[CDAR-703]: https://usdot-carma.atlassian.net/browse/CDAR-703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update GMock matchers to use older API

- include/multiple_object_tracking/dynamic_object.hpp
Adds missing `#include <variant>` to `dynamic_object.hpp`
Closes #136 
Closes [CDAR-704](https://usdot-carma.atlassian.net/browse/CDAR-704)
Compilation error
[CDAR-704]: https://usdot-carma.atlassian.net/browse/CDAR-704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Include <variant>

- scripts/install_dependencies.sh
This PR changes the Eigen dependency from being installed from source to being installed by apt. The installed version has also been reduced (implicitly) from 3.4 to 3.3.
Closes #141 
Closes [CDAR-713](https://usdot-carma.atlassian.net/browse/CDAR-712)
Most of our environments install Eigen 3.3, so it would be easier to install through apt.
[CDAR-713]: https://usdot-carma.atlassian.net/browse/CDAR-713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change Eigen to apt dependency

- include/multiple_object_tracking/fusing.hpp
- include/multiple_object_tracking/unscented_kalman_filter.hpp
- include/multiple_object_tracking/unscented_transform.hpp
- test/test_fusing.cpp
- test/test_temporal_alignment.cpp
This PR fixes a bug that caused numerical issues when doing covariance intersection or unscented Kalman filter predictions. When CTRV and CTRA state vectors get converted to `Eigen::Matrix` types, they lose the auto-wrap feature for angle values. We have to manually wrap them to avoid numerical issues.
> [!NOTE]
> These changes will affect the tracking library's performance for general cases. We are changing the implementation to support a specific use case. We will revisit a more robust fix in the future when time allows.
Closes #143
Closes [CDAR-716](https://usdot-carma.atlassian.net/browse/CDAR-716)
Bug fix
Manually in downstream packages.
[CDAR-716]: https://usdot-carma.atlassian.net/browse/CDAR-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
> Wrap angle values when dealing with Eigen

- include/multiple_object_tracking/track_management.hpp
This PR changes how the track manager demotes/removes confirmed tracks. In the proposed implementation change, _confirmed_ tracks never get demoted to _tentative_. _Confirmed_ tracks have a high probability of existing, so they likely have disappeared once we stop receiving associated detections. In this case, we want to stop managing that track entirely. If the same object appears again, we will create a new track for it.
_Confirmed_ tracks will now be removed if they don't receive an association in a specified number of times in a row. Additionally, there is an occurrence count cap. This is to prevent occurrence counts from reaching large numbers, which prevents invalid tracks from being removed in a timely manner. This was the original bug that this PR resolves.
Closes …
> Fix track manager's handling of confirmed tracks

- test/test_track_management.cpp
in this PR, https://github.com/usdot-fhwa-stol/multiple_object_tracking/pull/146
we updated how track manager treats confirmed tracks. This PR is to fix the unit test according to that
https://usdot-carma.atlassian.net/browse/CDAR-801
master release prep for 4.5.0
unit tested
> Fix unit test track managemet
